### ISSUE TITLE
NULL successfully deserializes into `u8`, `i8`, and `bool`

### ISSUE THREAD

**Issue by MasterPtato** [loyd/clickhouse.rs#100]
For most types trying to deserialize a NULL value into it would result in a `NotEnoughData` error, but for `u8`, `i8`, and `bool` the query doesn't fail. I'm guessing this is because all of these types have a size of 8 bytes.

I would expect this to fail the same way as other types do when trying to deserialize NULL without an `Option` wrapper.

```rust
#[derive(Debug, clickhouse::Row, serde::Deserialize)]
struct Row {
	value1: bool,
	value2: u8,
	value3: i8,
}

let res = client
	.query("SELECT NULL AS value1, NULL AS value2, NULL AS value3")
	.fetch_one::<Row>()
	.await
	.unwrap();

assert_eq!(true, res.value1);
assert_eq!(1, res.value2);
assert_eq!(1, res.value3);
```

Strangely enough the value isn't even 0/false, its 1/true.

clickhouse.rs version 0.11.2

**Comment by loyd** [comment]
Hello,

Nullable fields have the `Nullable(T)` type, not `T`. They are encoded as `1` if `NULL` and `0|T` if not `NULL`.

Thus, this is expected behavior (in both cases, `NotEnoughData` and successful `*8/bool`). In case of schema mismatch, the behavior is undefined (usually `NotEnoughData`, though).

It can be improved by moving to `RowBinaryWIthNamesAndTypes` (now `RowBinary` is used) in https://github.com/loyd/clickhouse.rs/issues/10.

Closed as a duplicate.
