### ISSUE TITLE
Still in active development?

### ISSUE THREAD

**Issue by gd87429** [loyd/clickhouse.rs#45]
Looks like not much weekly activity on `master` since June. Project still going strong?

**Comment by loyd** [comment]
It's actively used and supported.

What about development:
* I'm waiting for spreading GATs to fix borrowing fetching API (https://github.com/loyd/clickhouse.rs/issues/24).
* I'm planning (and have already performed some groundwork) to move to `RowBinaryWithNamesAndTypes` in order to support conversions between types (https://github.com/loyd/clickhouse.rs/issues/10).
