### ISSUE TITLE
HTTPS url throws error

### ISSUE THREAD

**Issue by jonasbostoen** [loyd/clickhouse.rs#58]
I've looked into the PRs and https urls should work, but I'm still getting an error. Double checked that the `tls` feature is enabled:
```
Network(hyper::Error(Connect, "invalid URL, scheme is not http"))
```
This happens when executing a query:
```rs
let result = client.query("SELECT 1").fetch_one::<usize>().await.unwrap();
```
Am I doing something wrong or is this a bug?

**Comment by makorne** [comment]
I have the same error.
Looks like there need test with https.

**Comment by eabz** [comment]
I was facing the same issue and managed to solve it by using my own hyper server.


```rust
        let https = HttpsConnector::new();

        let client = hyper::Client::builder().build::<_, hyper::Body>(https);

        let db = Client::with_http_client(client)
            .with_url(db_host)
            .with_user(db_username)
            .with_password(db_password)
            .with_database(db_name);
```

**Comment by jonasbostoen** [comment]
@eabz used the same workaround for now, ty

**Comment by ta3pks** [comment]
I saw a pr merged like 2 years ago fixing this issue was it reverted for some reason ?

**Comment by MasterPtato** [comment]
The issue seems to stem from the fact that [`HttpConnector.enforce_http`](https://docs.rs/hyper/latest/hyper/client/connect/struct.HttpConnector.html#method.enforce_http) is not set to `false` when the tls flag is enabled. I believe this is why @eabz 's workaround works ([relevant source code in `HttpsConnector::new`](https://docs.rs/hyper-tls/latest/src/hyper_tls/client.rs.html#50))

**Comment by loyd** [comment]
It's a shame that this issue has existed for too long. It's better to have some fixes, even without checks in CI. I've created a dedicated issue for CI after spending half an hour trying to do it during this one.

Thanks to @MasterPtato for the direct tip. It seems to fix the problem.

My company doesn't use CH with HTTPs for now, so I'll be glad if someone can check this fix in an actual setup.

Another question is whether TLS error should have another variant in `enum Error` because it's an unrecoverable error.

**Comment by namn-grg** [comment]
Hi, I am still getting the same error

initialization -
```
let db = Client::default()
            .with_url(db_host)
            .with_user(db_user)
            .with_password(db_password)
            .with_database(db_name);
```

error -
```
Error: Clickhouse error: network error: client error (Connect)

Caused by:
   0: network error: client error (Connect)
   1: client error (Connect)
   2: invalid URL, scheme is not http
 ```
 
if I do change the URL to HTTP then I get error -
```
Error: Clickhouse error: network error: client error (SendRequest)

Caused by:
   0: network error: client error (SendRequest)
   1: client error (SendRequest)
   2: connection error
   3: Connection reset by peer (os error 104)
```
